name: 1.18 Issue Report
description: Report an issue with the 1.18 alphas of Minecraft
labels: [1.18, Bug, Unreviewed]
body:
  - type: markdown
    attributes:
      value: |
        Please note that 1.18 versions of the mod are in alpha, so are subject to change. Before submitting an issue, please search the following links to make sure your issue is not covered:
        
        * **[Pinned Issues](/SlimeKnights/TinkersConstruct/issues)**: Some commonly reported issues are pinned
        * **[Roadmap](/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-Roadmap)**: Discusses unimplemented features and planned new changes
        * **[What's New](/SlimeKnights/TinkersConstruct/wiki/New-in-Tinkers%27-Construct-3)**: Discusses many of the major changes in the 1.18 alphas
        * **[FAQ](/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ)**: Answers to many frequently asked questions about the 1.18 versions
        
        Please fill in the following template to report your issue.
        
  - type: markdown
    attributes:
      value: "## Versions"
  
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      value: 1.18.1
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      placeholder: "Ex: 36.1.0"
    validations:
      required: true
  - type: input
    id: mantle-version
    attributes:
      label: Mantle Version
    validations:
      required: true
  - type: input
    id: tinkers-version
    attributes:
      label: "Tinkers' Construct Version"
      description: "'Latest' is not a valid answer, write an exact version number"
    validations:
      required: true
  
 
  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true
  
  - type: input
    id: crash-report
    attributes:
      label: Crash Report
      description: Paste a link to the crash report, if present
    validations:
      required: false
      
  - type: textarea
    id: required-mods
    attributes:
      label: Other mods
      description: List the smallest set of mods you have used to reproduce this issue. Please do not list a modpack name unless the modpack is public
    validations:
      required: true
        
        
  - type: markdown
    attributes:
      value: "## Confirm the following"
      
  - type: dropdown
    id: just-tinkers
    attributes:
      label: "Tried reproducing with just Tinkers?"
      description: "Test by removing all other mods besides Tinkers' Construct"
      options:
        - 'Yes'
        - 'I will go do that now'
        - 'No'
    validations:
      required: true
      
  - type: dropdown
    id: performance-enhancers
    attributes:
      label: "Performance Enchancers"
      description: "Select all that you were using when you reproduced the issue. Ideally reproduce with fewer performance enhancers."
      multiple: true
      options:
        - 'Magnesium'
        - 'Optifine'
        - 'Performant'
        - 'Other (specify under mods required)'
        - 'None'
    validations:
      required: true
      
  - type: dropdown
    id: searched
    attributes:
      label: "Searched for an existing issue?"
      description: "Please check [pinned issues](https://github.com/SlimeKnights/TinkersConstruct/issues) and try the [search bar](https://github.com/SlimeKnights/TinkersConstruct/issues)."
      options:
        - 'Checked pinned issues'
        - 'Used the search bar'
        - 'Checked pinned issues and used the search bar'
        - 'I did not try to find an existing issue'
    validations:
      required: true
      
  - type: dropdown
    id: faq
    attributes:
      label: "Checked FAQ?"
      description: "Did you check [the FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/Tinkers%27-Construct-3-FAQ) to see if your issue is covered?"
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
